services:

  blockchain:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
    # logging:
    #   driver: none 

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    logging:
      driver: none 

  listener:
    depends_on:
      - blockchain
      - database
    build:
      context: ./
      dockerfile: blockchain/Dockerfile
    environment:
      GANACHE_HOST: blockchain
      DB_HOST: database
    volumes:
      - "contracts:/eleos/blockchain/build/contracts"

  backend:
    depends_on:
      - blockchain
      - database
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: backend/Dockerfile
    environment:
      DB_HOST: database
      API_PORT: 8080
  
  frontend:
    depends_on:
      - blockchain
      - backend
    ports:
      - 80:3000
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      API_BASEURL: http://localhost:8080
      GANACHE_BASEURL: http://localhost:8545
    volumes:
      - "contracts:/eleos/frontend/static"

volumes:
  contracts: