hide footbox
hide members
hide circle

skinparam Sequence {
    MessageAlign center
}
skinparam ParticipantPadding 10
skinparam SequenceGroupBodyBackGroundColor ffffff90
skinparam DefaultTextAlignment center
skinparam Shadowing false
skinparam MinClassWidth 110

