name: Test Backend
on: [push, pull_request]

jobs:
  backend-ci:

    runs-on: ubuntu-latest

    services:
    
      ganache:
        image: trufflesuite/ganache-cli
        ports:
          - 8545:8545

      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test
        ports:
          - 27017:27017

    steps: 
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Merge to master
        if: ${{ !env.ACT }}
        run: git checkout --progress --force ${{ github.sha }}
      
      - name: Setup node (If running in Github Actions)
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Setup node (If running locally via act)
        if: ${{ env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run linter
        working-directory: ./backend
        run: npm run lint
      
      - name: Run tests
        working-directory: ./backend
        run: npm run test