name: Test Frontend
on: [push, pull_request]

jobs:
  frontend-ci:

    runs-on: ubuntu-latest

    services:

      ganache:
        image: trufflesuite/ganache-cli
        ports:
          - 8545:8545

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Merge to master
        if: ${{ !env.ACT }}
        run: git checkout --progress --force ${{ github.sha }}

      - name: Setup node (If running in Github Actions)
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup node (If running locally via act)
        if: ${{ env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./blockchain
        run: npm install

      - name: Truffle
        working-directory: ./blockchain
        run: |
          npx truffle compile
          npx truffle migrate
          cp build/contracts/CampaignFactory.json ../frontend/static/

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run linter
        working-directory: ./frontend
        run: npm run lint

      - name: Run tests
        working-directory: ./frontend
        run: npm run test

      - name: Generate files
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './frontend/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
