name: Test Frontend
on: [push, pull_request]

jobs:
  frontend-ci:

    runs-on: ubuntu-latest

    steps: 
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Merge to master
        if: ${{ !env.ACT }}
        run: git checkout --progress --force ${{ github.sha }}
      
      - name: Setup node (If running in Github Actions)
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup node (If running locally via act)
        if: ${{ env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run linter
        working-directory: ./frontend
        run: npm run lint
      
      - name: Run tests
        working-directory: ./frontend
        run: npm run test